# app/config/config.yml
liip_imagine:
    driver: "gd"
    filter_sets:
        # the name of the "filter set"
        thumbnail:
            quality: 55
            filters:
                scale:
                    dim: [120, 90 ]
                    mode: outbound
                    # create a 2px black border: center the thumbnail on a black background
                    # 4px larger to create a 2px border around the final image
                    background:
                        dim: [600, 300]
                        position: center
                        color: '#FFFFFF'
        miniature:
            quality: 75
            filters:
                scale:
                    dim: [600, 300 ]
                    mode: outbound
        welcome:
            quality: 75
            filters:
                scale:
                    dim: [1200, 1200 ]
                    mode: outbound
        full:
            quality: 85
            filters:
                scale:
                    dim: [1500, 1500 ]
                    mode: outbound

