vich_uploader:
    db_driver: orm

    mappings:
       realisation_images:
           uri_prefix: '%realisation_images%'
           upload_destination: '%kernel.project_dir%/public%realisation_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       blogpost_images:
           uri_prefix: '%blogpost_images%'
           upload_destination: '%kernel.project_dir%/public%blogpost_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       attachment_images:
           uri_prefix: '%attachment_images%'
           upload_destination: '%kernel.project_dir%/public%attachment_images%'
        #    inject_on_load: false
        #    delete_on_update: true
        #    delete_on_remove: true
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

