vich_uploader:
    db_driver: orm

    mappings:
       realisation_images:
           uri_prefix: '%realisation_images%'
           upload_destination: '%kernel.project_dir%/public/%realisation_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update:false
           delete_on_remove:false
